<?php
/**             
 * Caminho module/Modulo/view/modulo/${ctrlName}/view.phtml
 */

$title = 'Ver ${CtrlName}';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="collapse navbar-collapse">
	<ul class="nav navbar-nav">
	    <li>
	        <a href="<?php echo $this->url('${ctrlName}', array('action'=>'add'));?>">  
	            <?php echo $this->translate('Criar novo registro') ?>
	        </a>
	    </li>
	    <li>
	        <a href="<?php echo $this->url('${ctrlName}', array('action'=>'delete', 'id' => $this->${id}));?>">  
	            <?php echo $this->translate('Remover registro') ?>
	        </a>
	    </li>
	    <li>
	        <a href="<?php echo $this->url('${ctrlName}', array('action'=>'edit', 'id' => $this->${id}));?>"> 
	            <?php echo $this->translate('Editar registro') ?>
	        </a>
	    </li>
	    <li>
	        <a href="<?php echo $this->url('${ctrlName}', array('action'=>'pedidos', 'id' => $this->${id}));?>"> 
	            <?php echo $this->translate('Ver Pedidos') ?>
	        </a>
	    </li>
	</ul>
</div>
<br />

${cpsNames}




